apiVersion: v1
kind: Pod

metadata:
  name: l8r
  labels:
    app: l8r

spec:
  restartPolicy: OnFailure
  containers:
  - name: l8r
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args:
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-aks.ngsamem.svc.cluster.local:4120
    - http://ngsa-aks.ngsacos.svc.cluster.local:4120
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: l8r
