apiVersion: v1
kind: Pod

metadata:
  name: webv-stress
  labels:
    app: webv-stress

spec:
  serviceAccountName: k8s-admin
  restartPolicy: OnFailure
  containers:
  - name: app
    image: retaildevcrew/webvalidate:beta
    imagePullPolicy: Always
    args:
    - -l
    - "10"
    - -r
    - -v
    - -s
    - http://ngsa-aks.ngsamem.svc.cluster.local:4120
    - http://ngsa-aks.ngsacos.svc.cluster.local:4120
    - -u
    - https://raw.githubusercontent.com/retaildevcrews/ngsa/main/TestFiles/
    - -f
    - benchmark.json

  - name: log
    imagePullPolicy: Always
    image: retaildevcrew/logagent:beta
    env:
    - name: WorkspaceId
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: WorkspaceId
    - name: SharedKey
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: SharedKey
    - name: LogName
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: LogName
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region
    - name: NodeName
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: PodName
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: PodNamespace
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: PodIP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
