---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  template:
    metadata:
      labels:
        app: ngsa-memory
        version: beta-rc01    
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --in-memory
      - -z
      - Az-CentralUS
      - -r
      - Central
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta
    cert:
      enabled: false
      name: ngsa-cert
    ingress:
      hosts:
      - ngsa-mem-pre-central.cse.ms
      - alpha-ngsa-mem-pre-central.cse.ms
      - nmpc.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
