---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ngsa-cosmos
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: joaquinrz-prerelease
  template:
    metadata:
      labels:
        app: ngsa-cosmos
        version: beta-rc01    
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --no-cache
      zone: Az-CentralUS
      region: Central
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta
    cert:
      enabled: false
      name: ngsa-cert
    ingress:
      hosts:
      - ngsa-cos-pre-central.cse.ms
      - alpha-ngsa-cos-pre-central.cse.ms
      - ncpc.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
