---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: joaquinrz-prerelease
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --in-memory
      zone: Az-CentralUS
      region: Central
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta
    cert:
      enabled: false
      name: ngsa-cert
    ingress:
      hosts:
      - ngsa-mem-pre-central.cse.ms
      - alpha-ngsa-mem-pre-central.cse.ms
      - nmpc.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
