apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: fluentbit-csi-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: fluentbit-secrets
    type: Opaque
    data:
    - objectName: WorkspaceId
      key: WorkspaceId
    - objectName: SharedKey
      key: SharedKey
  parameters:
    usePodIdentity: "true"
    keyvaultName: "$KEYVAULT_NAME"
    objects: |
      array:
        - |
          objectName: WorkspaceId
          objectType: secret
        - |
          objectName: SharedKey
          objectType: secret
    tenantId: "$TENANT_ID"
