apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ngsa-csi-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: ngsa-secrets
    type: Opaque
    data:
    - objectName: CosmosDatabase
      key: CosmosDatabase
    - objectName: CosmosCollection
      key: CosmosCollection
    - objectName: CosmosKey
      key: CosmosKey
    - objectName: CosmosUrl
      key: CosmosUrl
  parameters:
    usePodIdentity: "true"
    keyvaultName: "$KEYVAULT_NAME"
    objects: |
      array:
        - |
          objectName: CosmosDatabase
          objectType: secret
        - |
          objectName: CosmosCollection
          objectType: secret
        - |
          objectName: CosmosKey
          objectType: secret
        - |
          objectName: CosmosUrl
          objectType: secret
    tenantId: "$TENANT_ID"
