apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: $NGSA_MI_NAME
spec:
  type: 0
  resourceID: $NGSA_MI_RESOURCE_ID
  clientID: $NGSA_MI_CLIENT_ID

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ${NGSA_MI_NAME}-binding
spec:
  azureIdentity: $NGSA_MI_NAME
  selector: $NGSA_MI_NAME
