apiVersion: v1
kind: Pod
metadata:
  name: helium-csharp
spec:
  containers:
  - name: helium-csharp
    image: retaildevcrew/helium-k8s-csharp:beta
    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"
  volumes:
  - name: secrets
    secret:
      secretName: helium-secrets
      defaultMode: 444
