# Default values for NGSA.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: retaildevcrew
  name: ngsa
  tag: beta

ingress:
  hosts:
    - ${Ngsa_App_Endpoint}
  paths:
    - /

app:
  args: []
  region: "Debug"
  zone: "Debug"

cert:
  name: ngsa-cert
