apiVersion: v1
kind: Pod
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  containers:
  - name: ngsa
    image: retaildevcrew/ngsa:beta
    args: [ "--in-memory" ]
    ports:
    - containerPort: 4120
