apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.15-alpine
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: www
      mountPath: /var/www
    - name: conf
      mountPath: /etc/nginx/conf.d
    - name: certbot
      mountPath: /etc/letsencrypt
    imagePullPolicy: Always
  volumes:
  - name: www
    hostPath:
      path: /home/nginx/www
      type: Directory
  - name: conf
    hostPath:
      path: /home/nginx/conf.d
      type: Directory
  - name: certbot
    hostPath:
      path: /home/nginx/certbot
      type: Directory

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  clusterIP:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort:
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - nodePort:
    name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
