apiVersion: v1
kind: Pod
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  containers:
  - name: ngsa
    image: retaildevcrew/ngsa:beta
    ports:
    - containerPort: 4120
    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"
    imagePullPolicy: Always
  volumes:
  - name: secrets
    secret:
      secretName: ngsa-secrets
      defaultMode: 444
