apiVersion: v1
kind: Pod
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  containers:
  - name: ngsa
    image: retaildevcrew/ngsa:beta
    ports:
    - containerPort: 4120
    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"
    imagePullPolicy: Always
  volumes:
  - name: secrets
    secret:
      secretName: ngsa-secrets
      defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  clusterIP:
  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
  selector:
    app: ngsa
  sessionAffinity: None
  type: ClusterIP
