apiVersion: v1
kind: Pod

metadata:
  name: webv
  labels:
    app: webv

spec:
  serviceAccountName: k8s-admin
  containers:
  - name: webv
    image: retaildevcrew/webvalidate:beta
    imagePullPolicy: Always
    args: ["-v", "-r", "-s", "http://ngsa:4120", "-u", "https://raw.githubusercontent.com/retaildevcrews/ngsa/main/TestFiles/", "-f", "benchmark.json", "-l", "1000"]

  - name: logagent
    imagePullPolicy: Always
    image: retaildevcrew/logagent:beta
    ports:
    - name: app
      containerPort: 3000
    env:
    - name: WorkspaceId
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: WorkspaceId
    - name: SharedKey
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: SharedKey
    - name: LogName
      value: bartrsc
    - name: NodeName
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: PodName
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: PodNamespace
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: PodIP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
