apiVersion: v1
kind: Pod
metadata:
  name: webv
  labels:
    app: webv
spec:
  containers:
  - name: webv
    image: retaildevcrew/webvalidate:beta
    imagePullPolicy: Always
    args: ["-s", "http://ngsa", "-u", "https://raw.githubusercontent.com/retaildevcrews/helium/main/TestFiles/", "-f", "benchmark.json", "-r", "-l", "1000"]
