apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  serviceAccountName: k8s-admin
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa:beta
    args: [ "--in-memory" ]
    ports:
    - containerPort: 4120

  - name: log
    imagePullPolicy: Always
    image: retaildevcrew/logagent:beta
    env:
    - name: WorkspaceId
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: WorkspaceId
    - name: SharedKey
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: SharedKey
    - name: LogName
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: LogName
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: webv-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: webv-config
          key: Region
    - name: NodeName
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: PodName
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: PodNamespace
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: PodIP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  clusterIP:
  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
  selector:
    app: ngsa-memory
  sessionAffinity: None
  type: ClusterIP
