apiVersion: v1
kind: Pod
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  serviceAccountName: k8s-admin
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa:beta

    ports:
    - containerPort: 4120

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"

  - name: log
    imagePullPolicy: Always
    image: retaildevcrew/logagent:new

    env:
    - name: WorkspaceId
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: WorkspaceId
    - name: SharedKey
      valueFrom:
        secretKeyRef:
          name: ngsa-secrets
          key: SharedKey
    - name: LogName
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: LogName
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region
    - name: NodeName
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: PodName
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: PodNamespace
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: PodIP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

  volumes:
  - name: secrets
    secret:
      secretName: ngsa-secrets
      defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  sessionAffinity: None
  type: ClusterIP

  selector:
    app: ngsa-cosmos

  clusterIP:

  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
