apiVersion: v1
kind: Pod

metadata:
  name: webv-baseline
  labels:
    app: webv-baseline

spec:
  restartPolicy: Never
  containers:
  - name: webv
    image: retaildevcrew/webv:beta
    imagePullPolicy: Always
    args: ["-s", "http://ngsa-memory:4120", "http://ngsa-cosmos:4120", "-u", "https://raw.githubusercontent.com/retaildevcrews/ngsa/main/TestFiles/", "-f", "baseline.json"]
    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region
    - name: PodType
      value: webv
