apiVersion: v1
kind: Pod

metadata:
  name: benchmark
  labels:
    app: benchmark

spec:
  serviceAccountName: k8s-admin
  restartPolicy: OnFailure
  containers:
  - name: app
    image: retaildevcrew/webv:beta
    imagePullPolicy: Always
    args: ["--duration", "3600", "-r", "-v", "-s", "http://ngsa-memory:4120", "http://ngsa-cosmos:4120", "-u", "https://raw.githubusercontent.com/retaildevcrews/ngsa/main/TestFiles/", "-f", "baseline.json"]
    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region
    - name: PodType
      value: webv

