apiVersion: v1
kind: Pod
metadata:
  name: ngsa
  labels:
    app: ngsa

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa:beta

    ports:
    - containerPort: 4120

    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  sessionAffinity: None
  type: ClusterIP

  selector:
    app: ngsa-cosmos

  clusterIP:

  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
