---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
    filter.fluxcd.io/ds: glob:beta-*
spec:
  releaseName: ngsa-cosmos
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  values:
    app:
      args: []
      secretName: ngsa-secrets
      image:
        repository: retaildevcrew/ngsa-app
        tag: beta-0.1.1-0205-1555-178
    ds:
      args:
      - --no-cache
      secretName: ngsa-secrets
      image:
        repository: retaildevcrew/ngsa-dataservice
        tag: beta-0.1.1-0205-1556-178
    cert:
      enabled: false
    ingress:
      hosts:
      - ngsa-cos-dev.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
