---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --in-memory
      - -z
      - dev
      - -r
      - dev
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta-0.1.1-0305-0620-14
    cert:
      enabled: false
    ingress:
      hosts:
      - ngsa-mem-dev.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
