apiVersion: v1
kind: Pod
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-app:beta
    ports:
    - containerPort: 4120
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: 250m

  - name: ds
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-dataservice:beta
    args:
    - --no-cache
    ports:
    - containerPort: 4122
    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 512Mi
        cpu: 500m

  volumes:
  - name: secrets
    secret:
      secretName: ngsa-secrets
      defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  sessionAffinity: None
  type: ClusterIP

  selector:
    app: ngsa-cosmos

  clusterIP:

  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
