apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{  include "fluentbit.fullname" . }}
  labels:
    app.kubernetes.io/component: fluentbit
    {{- include "fluentbit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fluentbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fluentbit
        {{- include "fluentbit.labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: {{ include "fluentbit.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: fluentbit
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-secrets
                  key: WorkspaceId
            - name: SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-secrets
                  key: SharedKey
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-log-config
                  key: region
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-log-config
                  key: zone
            - name: NGSA_LOG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-log-config
                  key: ngsaLog
            - name: LODE_LOG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fluentbit.fullname" . }}-log-config
                  key: lodeLog
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: {{ include "fluentbit.fullname" . }}
