apiVersion: v1
kind: Pod

metadata:
  name: l8r-load-100
  labels:
    app: l8r-load-100

spec:
  restartPolicy: OnFailure
  containers:
  - name: l8r
    image: retaildevcrew/ngsa-loderunner:beta
    imagePullPolicy: Always
    args:
    - -l
    - "10"
    - -r
    - -s
    - http://ngsa-memory.ngsa:4120
    - http://ngsa-cosmos.ngsa:4120
    - -f
    - benchmark.json
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 512Mi
      type: Container
