apiVersion: v1
kind: Pod

metadata:
  name: l8r-load-200
  labels:
    app: l8r-load-200

spec:
  restartPolicy: OnFailure
  containers:
  - name: l8r
    image: retaildevcrew/ngsa-loderunner:beta
    imagePullPolicy: Always
    args:
    - -l
    - "5"
    - --duration
    - "60"
    - -r
    - -s
    - http://ngsa-memory.ngsa:4120
    - http://ngsa-cosmos.ngsa:4120
    - -f
    - benchmark.json
