apiVersion: v1
kind: Pod

metadata:
  name: l8r-load-500
  labels:
    app: l8r-load-500

spec:
  restartPolicy: OnFailure
  containers:
  - name: l8r
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args:
    - -l
    - "2"
    - --duration
    - "60"
    - -r
    - -s
    - http://ngsa-memory.ngsa.svc.cluster.local:4120
    - http://ngsa-cosmos.ngsa.svc.cluster.local:4120
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: l8r-load-500
