apiVersion: v1
kind: Pod

metadata:
  name: l8r-load-200
  labels:
    app: l8r-load-200

spec:
  restartPolicy: OnFailure
  containers:
  - name: l8r
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always
    args:
    - -l
    - "5"
    - --duration
    - "60"
    - -r
    - -s
    - http://ngsa-memory.ngsa:8080
    - http://ngsa-cosmos.ngsa:8080
    - -f
    - benchmark.json
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
