apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentbit.serviceAccountName" . }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fluentbit.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs: 
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "fluentbit.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentbit.fullname" . }}
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "fluentbit.serviceAccountName" . }}
    apiGroup: ""
