apiVersion: v1
kind: Pod

metadata:
  name: loderunner-baseline-memory
  labels:
    app: loderunner-baseline-memory

spec:
  restartPolicy: Never
  containers:
  - name: app
    image: retaildevcrew/ngsa-loderunner:beta
    imagePullPolicy: Always

    args: 
    - -s
    - http://ngsa-memory:4120
    - -f
    - baseline.json
