apiVersion: v1
kind: Pod

metadata:
  name: loderunner-benchmark-memory
  labels:
    app: loderunner-benchmark-memory

spec:
  restartPolicy: Always
  containers:
  - name: app
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args: 
    - -l
    - "1000"
    - -r
    - -s
    - http://ngsa-memory:4120
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: loderunner

