apiVersion: v1
kind: Pod

metadata:
  name: loderunner-benchmark-cosmos
  labels:
    app: loderunner-benchmark-cosmos

spec:
  restartPolicy: Always
  containers:
  - name: app
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args: 
    - -l
    - "1000"
    - -r
    - -s
    - http://ngsa-cosmos:4120
    - -f
    - benchmark.json
