apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  labels:
    app: loderunner
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'

spec:
  containers:
  - name: app

    image: retaildevcrew/ngsa-lr:beta
    imagePullPolicy: Always

    args: 
    - -l
    - "500"
    - -r
    - -s
    - http://ngsa-memory:8080
    - -f
    - benchmark.json

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner
  labels:
    app: loderunner
spec:
  type: NodePort
  selector:
    app: loderunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
