apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  labels:
    app: loderunner

spec:
  containers:
  - name: app

    image: retaildevcrew/ngsa-loderunner:beta
    imagePullPolicy: Always

    args: 
    - -l
    - "500"
    - -r
    - -s
    - http://ngsa-memory:8080
    - -f
    - benchmark.json

