apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  labels:
    app: loderunner

spec:
  containers:
  - name: app

    image: retaildevcrew/ngsa-loderunner:beta
    imagePullPolicy: Always

    args: 
    - -l
    - "1000"
    - -r
    - -s
    - http://ngsa-memory:4120
    - http://ngsa-cosmos:4120
    - -f
    - benchmark.json

    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
