---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-cosmos
  chart:
    git: https://github.com/retaildevcrews/ngsa.git
    path: spikes/aks-secure-baseline/charts/ngsa
    ref: spike/ngsa-pnp
  values:
    app:
      args:
      - --no-cache
      secretName: ngsa-secrets
      image:
        repository: acraksioxqpbmcqokqq.azurecr.io/retaildevcrews/ngsa-app
        tag: beta
      resources:
        limits:
          cpu: 1
          memory: 512Mi
