---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: https://github.com/retaildevcrews/ngsa.git
    path: spikes/aks-secure-baseline/charts/ngsa
    ref: spike/ngsa-pnp
  values:
    app:
      args:
      - --in-memory
      secretName: ngsa-secrets
      image:
        repository: acraksioxqpbmcqokqq.azurecr.io/retaildevcrews/ngsa-app
        tag: beta
    autoscaling:
      enabled: false
