apiVersion: v1
kind: Pod

metadata:
  name: l8r-baseline
  labels:
    app: l8r-baseline

spec:
  restartPolicy: Never
  containers:
  - name: l8r
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args:
    - -s
    - http://ngsa-memory:4120
    - http://ngsa-cosmos:4120
    - -f
    - baseline.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: l8r-baseline
