apiVersion: v1
kind: Pod

metadata:
  name: l8r-benchmark
  labels:
    app: l8r-benchmark

spec:
  serviceAccountName: k8s-admin
  restartPolicy: Never
  containers:
  - name: app
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always
    args: 
    - --duration
    - "3600"
    - -l
    - "1000"
    - -r
    - -s
    - http://ngsa-memory:4120
    - http://ngsa-cosmos:4120
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: l8r-benchmark

