kind: Namespace
apiVersion: v1
metadata:
  name: ngsa-memory-settings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ngsa-flux
  name: ngsa-flux
  namespace: ngsa-memory-settings
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ngsa-flux
  labels:
    app.kubernetes.io/name: ngsa-flux
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ngsa-flux
  labels:
    app.kubernetes.io/name: ngsa-flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngsa-flux
subjects:
  - kind: ServiceAccount
    name: ngsa-flux
    namespace: ngsa-memory-settings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-flux
  namespace: ngsa-memory-settings
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngsa-flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      labels:
        app.kubernetes.io/name: ngsa-flux
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: npuser01
      serviceAccountName: ngsa-flux
      volumes:
      - name: git-key
        secret:
          secretName: ngsa-flux-git-deploy
      containers:
      - name: ngsa-flux
        # PRODUCTION READINESS CHANGE REQUIRED
        # This image should be sourced from a non-public container registry, such as the
        # one deployed along side of this reference implementation.
        # az acr import --source docker.io/fluxcd/flux:1.19.0 -n <your-acr-instance-name>
        # and then set this to
        # image: <your-acr-instance-name>.azurecr.io/fluxcd/flux:1.19.0
        image: docker.io/fluxcd/flux:1.21.1
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          # create folder in the root fs when cloning repos
          readOnlyRootFilesystem: false
          # access to root folder like /.kube/config
          runAsNonRoot: false
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 3030
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        args:
        - --git-url=https://github.com/retaildevcrews/gitops.git
        - --git-branch=main
        - --git-path=deploy/dev-central/ngsa
        # this configuration prevents flux from syncing changes from your cluster to the git repo. If two way sync is required, please take a look at  https://docs.fluxcd.io/en/1.19.0/tutorials/get-started/#giving-write-access
        - --git-readonly
        - --sync-state=secret
        - --listen-metrics=:3031
        - --git-timeout=2m
        - --registry-disable-scanning=true
        - --k8s-secret-name=ngsa-flux-git-deploy
---
# This secret is ok to be initialized as empty since Flux annotates the
# Kubernetes Secret object with flux.weave.works/sync-hwm: <commit-sha>
# as a way to store the latest commit applied to the cluster and later on
# compare with to confirm wether it is in sync or not.
apiVersion: v1
kind: Secret
metadata:
  name: ngsa-flux-git-deploy
  namespace: ngsa-memory-settings
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memcached
  namespace: ngsa-memory-settings
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngsa-memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ngsa-memcached
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: npuser01
      containers:
      - name: ngsa-memcached
        # PRODUCTION READINESS CHANGE REQUIRED
        # This image should be sourced from a non-public container registry, such as the
        # one deployed along side of this reference implementation.
        # az acr import --source docker.io/library/memcached:1.5.20 -n <your-acr-instance-name>
        # and then set this to
        # image: <your-acr-instance-name>.azurecr.io/library/memcached:1.5.20
        image: library/memcached:1.5.20
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 512Mi
        args:
        - -m 512
        - -I 5m    # Maximum size for one item
        - -p 11211 # Default port
        # - -vv    # Uncomment to get logs of each request and response.
        ports:
        - name: clients
          containerPort: 11211
        securityContext:
          runAsUser: 11211
          runAsGroup: 11211
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-memcached
  namespace: ngsa-memory-settings
spec:
  ports:
    - name: ngsa-memcached
      port: 11211
  selector:
    app.kubernetes.io/name: ngsa-memcached
