apiVersion: v1
kind: Pod

metadata:
  name: l8r
  labels:
    app: l8r

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: retaildevcrew/loderunner:beta
    imagePullPolicy: Always

    args:
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-memory:4120
    - http://ngsa-cosmos:4120
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: l8r
