apiVersion: v1
kind: Pod

metadata:
  name: webv
  labels:
    app: webv

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: retaildevcrew/webvalidate:beta
    imagePullPolicy: Always
    args:
    - -l
    - "100"
    - -r
    - -v
    - -s
    - http://ngsa-memory:4120
    - http://ngsa-cosmos:4120
    - -u
    - https://raw.githubusercontent.com/retaildevcrews/ngsa/main/TestFiles/
    - -f
    - benchmark.json

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone
    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region
    - name: PodType
      value: l8r
