apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: ngsa
    imagePullPolicy: Always
    image: retaildevcrew/ngsa:beta
    args: [ "--in-memory" ]
    ports:
    - containerPort: 4120

    env:
    - name: Zone
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Zone

    - name: Region
      valueFrom:
        configMapKeyRef:
          name: ngsa-config
          key: Region

    - name: PodType
      value: ngsa-memory

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  clusterIP:
  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
  selector:
    app: ngsa-memory
  sessionAffinity: None
  type: ClusterIP
