apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: ngsa
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-dataservice:beta
    args: [ "--in-memory", "-l", "Warning" ]
    ports:
    - containerPort: 4122

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  clusterIP:
  ports:
  - port: 4122
    protocol: TCP
    targetPort: 4122
  selector:
    app: ngsa-memory
  sessionAffinity: None
  type: ClusterIP
