apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-app:beta
    ports:
    - containerPort: 4120
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: 250m

  - name: ds
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-dataservice:beta
    args: [ "--in-memory", "-l", "Warning" ]
    ports:
    - containerPort: 4122
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 512Mi
        cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  clusterIP:
  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
  selector:
    app: ngsa-memory
  sessionAffinity: None
  type: ClusterIP
