apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: ds
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-ds:beta
    args:
      - --in-memory
      - -l
      - Warning
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 512Mi
        cpu: 500m

---

apiVersion: v1
kind: Pod
metadata:
  name: ngsa-app
  labels:
    app: ngsa-app

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-ds:beta
    args: 
      - -a
      - WebAPI
      - -s
      - http://ngsa-memory:8080
      - -l
      - Warning
    ports:
    - containerPort: 4120
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
      requests:
        memory: 512Mi
        cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-app
  labels:
    app: ngsa-app
spec:
  clusterIP:
  ports:
  - port: 4120
    protocol: TCP
    targetPort: 4120
  selector:
    app: ngsa-app
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  clusterIP:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ngsa-memory
  sessionAffinity: None
  type: ClusterIP
