apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'

spec:
  containers:
  - name: ds
    imagePullPolicy: Always
    image: retaildevcrew/ngsa-ds:beta
    args:
      - --in-memory
      - -l
      - Warning
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  type: NodePort
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
