apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "ngsa.fullname" . }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
    - {{ . }}
  {{- end }}
    - {{ include "ngsa.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
  - {{ include "ngsa.fullname" . }}-gateway
  http:
  - match:
    {{- range .Values.ingress.paths }}
      - uri:
          prefix: {{ . }}
    {{- end }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "ngsa.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
