---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-cosmos
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  values:
    app:
      args:
      - --no-cache
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta-0.1.1-0224-0741-3
    cert:
      enabled: false
      name: ngsa-cert
    ingress:
      hosts:
      - ngsa-cos-pre-west.cse.ms
      - alpha-ngsa-cos-pre-west.cse.ms
      - ncpw.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
