---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ngsa-memory
  namespace: ngsa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:beta-*
spec:
  releaseName: ngsa-memory
  chart:
    git: git@github.com:retaildevcrews/ngsa
    path: gitops/charts/ngsa
    ref: main
  values:
    autoscaling:
      enabled: false
    app:
      args:
      - --in-memory
      - -z
      - Az-WestUS2
      - -r
      - West
      secretName: ngsa-secrets
      image:
        repository: ghcr.io/retaildevcrews/ngsa-app
        tag: beta-0.3.0-0330-2146-26
    cert:
      enabled: false
      name: ngsa-cert
    ingress:
      hosts:
      - ngsa-mem-pre-west.cse.ms
      - alpha-ngsa-mem-pre-west.cse.ms
      - nmpw.cse.ms
      paths:
      - /
    gateway:
      name: wildcard-gateway
