name: Docker Build

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

    paths:
    - 'src/**'
    - 'Dockerfile'
    - '.github/workflows/appPR.yaml'

  push:
    branches:
      - main

    paths:
    - 'src/**'
    - 'Dockerfile'
    - '.github/workflows/appPR.yaml'

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      # copy the config value to environment variables
      # do not copy the actual secrets!

      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

      # These are used in if: conditions
      DOCKER_SET: false
      COSMOS_SET: false
      BUILD: true

    steps:
    - uses: actions/checkout@v2

    - name: Set conditions
      run: |
        # check that all Docker secrets are set
        if [[ "${{ secrets.DOCKER_PAT }}" != "" && "${{ secrets.DOCKER_REPO }}" != "" && "${{ secrets.DOCKER_USER }}" != "" ]];
        then
          echo "DOCKER_SET=true" >> $GITHUB_ENV
        fi
        
        if [[ "${{ secrets.CosmosUrl }}" != "" && "${{ secrets.CosmosKey }}" != "" ]];
        then
          echo '${{ secrets.CosmosUrl }}' > src/app/secrets/CosmosUrl
          echo '${{ secrets.CosmosKey }}' > src/app/secrets/CosmosKey
          echo "COSMOS_SET=true" >> $GITHUB_ENV
        fi

    - name: PR Closed
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && ! github.event.pull_request.merged }}

      run: |

        # handle PR Closed event by building / pushing main branch
        
        # checkout parent branch (usually "main")
        git config pull.ff only
        git fetch --all
        git checkout ${{ github.base_ref }}
        git pull

    - name: PR Merged
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}

      run: |

        # Do not build on PR Merged
        
        # Skip remaining steps
        echo "DOCKER_SET=false" >> $GITHUB_ENV
        echo "COSMOS_SET=false" >> $GITHUB_ENV
        echo "BUILD=false" >> $GITHUB_ENV

    - name: Docker Login
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Docker Pull Test
      if: ${{ env.BUILD == 'true' }}
      run: |
        # Pull the latest image if needed
        # This doesn't have to be a separate step, but makes the output easier to read and debug
        docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

    - name: Docker Build Test
      if: ${{ env.BUILD == 'true' }}
      run: |
        # build test image
        docker build . -t test --target test

    - name: Install WebV
      if: ${{ env.COSMOS_SET == 'true' }}
      run: |
        dotnet tool install -g webvalidate

    - name: Start helium container
      if: ${{ env.COSMOS_SET == 'true' }}
      run: |
        # run the app
        docker run -d --name ngsa -p 4120:4120 test
        
        echo "Waiting for web server to start and run initial tests ..."
        sleep 25

    - name: Run WebV
      if: ${{ env.COSMOS_SET == 'true' }}
      run: |
        # run web validation test
        # fail on any validation errors
        cd TestFiles
        webv -s localhost:4120 --max-errors 1 -f baseline.json
        cd ..

    - name: Display failed docker logs
      if: ${{ failure() }}
      run: |
        # display the results
        docker logs ngsa

    - name: Display coverage results
      if: ${{ env.COSMOS_SET == 'true' }}
      run: |
        # wait for helium to shutdown
        sleep 15

        # display the results
        docker logs ngsa | tail -n 15

    - name: Display full test results
      if: ${{ env.COSMOS_SET == 'true' }}
      run: |
        # display the results
        docker logs ngsa

    - name: Docker Pull Release
      if: ${{ env.BUILD == 'true' }}
      run: |
        # Pull the latest image if needed
        docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

    - name: Docker Build Release
      if: ${{ env.BUILD == 'true' }}
      run: |
        # build image
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then
          docker build . -t image --build-arg TAG=true
        else
          docker build . -t image
        fi
        
    - name: Docker Tag and Push
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # tag the repo with :beta
        docker tag image $DOCKER_REPO:beta

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'  | sed -e 's/^v//')

          # tag the image with :version and :latest
          docker tag image $DOCKER_REPO:$VERSION
          docker tag image $DOCKER_REPO:latest
        fi

        # Push to the repo
        docker push $DOCKER_REPO
